export enum ModuleCategory {
  SUBJECT_MODULE = "SUBJECT_MODULE",
  INTERDISCIPLINARY_MODULE = "INTERDISCIPLINARY_MODULE",
  CONTEXT_MODULE = "CONTEXT_MODULE",
  PROJECT_MODULE = "PROJECT_MODULE",
  BACHELOR_MODULE = "BACHELOR_MODULE",
  DISPENSED_PA_MODULE = "DISPENSED_PA_MODULE",
  DISPENSED_WPM_MODULE = "DISPENSED_WPM_MODULE",
  CONSECUTIVE_MODULE = "CONSECUTIVE_MODULE",
}

export default ModuleCategory;
